server:
    port: 3080
spring:
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/db_eventos
        username: postgres
        password: 1234

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create

