server:
    port: 3080
spring:
    sql:
        init:
            mode: always

    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/db_eventos
        username: postgres
        password: 1234

    jpa:
        defer-datasource-initialization: true
        show-sql: true
        hibernate:
            ddl-auto: none




