
spring:
    profiles:
        active: ${PROFILE}
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                enable_lazy_load_no_trans: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
            jdbc: 
                lob: 
                    non_contextual_creation: true


