// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('c:/Estacio/programacao_para_dispositivos_moveis_android/evento/evento v2/node_modules/react');
var { Component } = React;
var ReactNative = require('c:/Estacio/programacao_para_dispositivos_moveis_android/evento/evento v2/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('navegacao', appParameters);
});
require('c:/Estacio/programacao_para_dispositivos_moveis_android/evento/evento v2/index.js');